### PR TITLE
203 support php 8

### PR DESCRIPTION
**Pull request by daniel-sc**
when this is merged I'd like to cut a new (major) release :)

### CODE REVIEW

**Comment by daniel-sc** [comment]
Regarding the decreased coverage: Sadly the decreased value is the truth. The actual coverage is not changing. Before, all uncovered files were ignored for computing the coverage. :-/

**Comment by daniel-sc** [comment]
Not sure if I am missing something, but it seems to me that the "2 reviews" rule is not working very well - any suggestions?

**Comment by rafaelmb** [comment]
> Not sure if I am missing something, but it seems to me that the "2 reviews" rule is not working very well - any suggestions?

I was going to comment something alogn this lines. I do believe that with the amount of active contributors the reviewers could be reduced to 1. 

About the PR I did checked it out but didn't tested enough. Will try to do it today.

**Comment by bajarang-agarwal** [comment]
Hi @daniel-sc 

Thank you for raising this PR and actively contributing to this repository and upgrading the library.
I agree with @rafaelmb that we can reduce it to 1 reviewer.
I have gone through with the PR and it looks good to me as well but I did not get a chance to run the test.
I suggest that you already tested and if @rafaelmb gets a chance to test then we can merge it.

**Review by rafaelmb — APPROVED** [review]
LGTM

**Pull request merged**
