### PR TITLE
dropping support for php 5.x

### PR DESCRIPTION
**Pull request by daniel-sc**
...and add info in CONTRIBUTING.md for updating CHANGES.md

### CODE REVIEW

**Review by rafaelmb — COMMENTED** [review]
Is there any reason for dropping php 5 support? You know besides being old and unsafe? Just kidding Daniel but, I was wondering why keep php 7.1 and not 7.0 since both are in EOL state?

**Comment by daniel-sc** [comment]
Hi @rafaelmb 
Primary reason was that the Travis build was failing for 5. Besides this, I'd go with support for older versions such as 7.0 if there is no specific reason not to?
Generally I do _not_ have a good overview about php versions used in production (or by users of this lib) - so I'd follow your advice.

**Review by carlfredrikhero — APPROVED** [review]

**Review by rafaelmb — CHANGES_REQUESTED** [review]
I wish I could keep php 5.x but I have no idea what that build error is and this month I have no time to check it (that's good enough reason to drop 5.x to me). But if we can keep 7.0 it will be better https://blog.packagist.com/php-versions-stats-2020-1-edition/.

**Review by rafaelmb — APPROVED** [review]
LGTM thanks Daniel. Please let me know if anything below 7.2 crashes cause I have apps on this stack and  surely I can help.

**Pull request merged**
